// utils/actfile.js
module.exports = [
    {"codigo": "1", "descripcion": "JUEGO DE ESCUADRA GRANDE", "cantidad": 11, "venta": 1.00, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "2", "descripcion": "LAPICERO PAPER MATTE", "cantidad": 13, "venta": 0.20, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "3", "descripcion": "ESCARCHA DE SOBRE", "cantidad": 48, "venta": 0.20, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "4", "descripcion": "PINCEL ECONOMICO PLANO Y REDONDO", "cantidad": 6, "venta": 0.85, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "5", "descripcion": "STICKER PARA CUADERNO NOMBRE", "cantidad": 2, "venta": 1.00, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "6", "descripcion": "TIJERA FIGURAS", "cantidad": 2, "venta": 1.00, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "7", "descripcion": "PAQUETE DE CLIP", "cantidad": 2, "venta": 0.80, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "8", "descripcion": "PAQUETE ALFILERES ESCOLARES CHINCHE", "cantidad": 2, "venta": 0.80, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "9", "descripcion": "MARCADOR PERMANETE DOBLE PUNTA", "cantidad": 18, "venta": 0.50, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "10", "descripcion": "MARCADOR ACRILICO ECONOMICO", "cantidad": 30, "venta": 0.50, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "15", "descripcion": "PLASTILINA 6 UND MODELING", "cantidad": 20, "venta": 0.45, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "16", "descripcion": "PLASTILINA 10 UND GRANDE", "cantidad": 9, "venta": 0.70, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "17", "descripcion": "TIZA DE COLORES CAJA", "cantidad": 8, "venta": 0.90, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "18", "descripcion": "TIZA BLANCA CAJA", "cantidad": 12, "venta": 0.50, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "19", "descripcion": "COLORES CERA 6 UND", "cantidad": 5, "venta": 0.35, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "20", "descripcion": "COLORES CERA 12 UND", "cantidad": 5, "venta": 0.70, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "21", "descripcion": "COLORES FAMOZOZ 12 UND", "cantidad": 6, "venta": 1.20, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "22", "descripcion": "COLORES PASTELES CRISVI 12UND", "cantidad": 4, "venta": 1.50, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "23", "descripcion": "COLORES MAKSIM 12 UND", "cantidad": 2, "venta": 1.30, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "24", "descripcion": "KIT PORTAMINA 6 PIEZAS", "cantidad": 8, "venta": 1.30, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "25", "descripcion": "RESALTADOR DELGADO 6 UND", "cantidad": 1, "venta": 1.50, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "26", "descripcion": "MARCADOR ARTEZA 6 UND", "cantidad": 3, "venta": 0.60, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "27", "descripcion": "CAJA MARCADOR WEIBO 12 DOBLE P", "cantidad": 5, "venta": 2.50, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "28", "descripcion": "RESALTADOR CUADRADO KEIROAD 4 UND", "cantidad": 6, "venta": 2.10, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "29", "descripcion": "KIT MARACADOR + BORRADOR ACRILICO", "cantidad": 6, "venta": 1.60, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "30", "descripcion": "CARTUCHERA 3 D", "cantidad": 2, "venta": 2.50, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "31", "descripcion": "CARTUCHERAS PLASTICAS", "cantidad": 8, "venta": 0.60, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "32", "descripcion": "CARTILLAS ESCOLAR", "cantidad": 2, "venta": 1.00, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "33", "descripcion": "EXACTO", "cantidad": 10, "venta": 0.30, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "34", "descripcion": "LIMPIA PIPA TRADICIONAL", "cantidad": 2, "venta": 2.00, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "35", "descripcion": "LIMPIA PIPA PELUDO", "cantidad": 1, "venta": 2.40, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "36", "descripcion": "POMPONES", "cantidad": 1, "venta": 2.40, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "37", "descripcion": "BOLSA TRANSPARENTE", "cantidad": 1, "venta": 1.80, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "101", "descripcion": "PAPEL BOND", "cantidad": 50, "venta": 0.25, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "103", "descripcion": "FOAMI UNICOLOR CARTA", "cantidad": 130, "venta": 0.20, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "104", "descripcion": "FOAMI UNICOLOR DOBLE CARTA", "cantidad": 90, "venta": 0.40, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "105", "descripcion": "FOAMI ESCARCHA CARTA", "cantidad": 176, "venta": 0.35, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "106", "descripcion": "FOAMI ESCARCHA DOBLE CARTA", "cantidad": 70, "venta": 0.50, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "107", "descripcion": "RESMA DE HOJA CARTA BLANCA 500 UND", "cantidad": 1, "venta": 6.00, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "108", "descripcion": "MEDIA RESMA DE HOJA BLANCA 250 UND", "cantidad": 2, "venta": 3.30, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "109", "descripcion": "HOJAS BLANCA UND", "cantidad": 1350, "venta": 0.01, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "112", "descripcion": "HOJA OFICIO BLANCA UND", "cantidad": 450, "venta": 0.02, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "114", "descripcion": "HOJA DE EXAMEN UND", "cantidad": 250, "venta": 0.06, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "115", "descripcion": "CARTULINA ESCARCHADA PLIEGO", "cantidad": 20, "venta": 1.00, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "116", "descripcion": "CARTULINA FLUORESCENTE PLIEGO", "cantidad": 13, "venta": 0.75, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "117", "descripcion": "CARTULINA METALIZADA PLIEGO", "cantidad": 22, "venta": 1.00, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "118", "descripcion": "CARTULINA DOBLE FAX PLIEGO PEQUEÑA", "cantidad": 20, "venta": 0.85, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "119", "descripcion": "CARTULINA DOBLE FAX PLIEGO GRANDE", "cantidad": 12, "venta": 1.00, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "120", "descripcion": "CARTULINA BLANCA ESCOLAR Y COLOR", "cantidad": 80, "venta": 0.50, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "121", "descripcion": "PAPEL GREPPE", "cantidad": 170, "venta": 0.35, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "122", "descripcion": "BLOCK MILIMETRADO", "cantidad": 6, "venta": 1.50, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "123", "descripcion": "HOJA MILIMETRADO", "cantidad": 60, "venta": 0.10, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "124", "descripcion": "TALONARIO DE FACTURAS N1", "cantidad": 3, "venta": 1.30, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "125", "descripcion": "FICHA CRISVI 4X6 5 UND", "cantidad": 20, "venta": 0.20, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "126", "descripcion": "FICHA CRISVI 5X8 5 UND", "cantidad": 20, "venta": 0.30, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "127", "descripcion": "HOJA COLORES CARTA NEON", "cantidad": 45, "venta": 0.08, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "128", "descripcion": "BLOCK CARTULINA COLORES", "cantidad": 6, "venta": 1.50, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "129", "descripcion": "BLOCK DE CONSTRUCCION", "cantidad": 0, "venta": 0.00, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "130", "descripcion": "BLOCK PAPEL LUSTRILLO", "cantidad": 16, "venta": 1.35, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "131", "descripcion": "CARPETA LIGA UNICOLOR", "cantidad": 8, "venta": 1.30, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "132", "descripcion": "CARPETA LIGA ESTANPADA", "cantidad": 12, "venta": 1.35, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "133", "descripcion": "CARPETA NEON CARTA", "cantidad": 8, "venta": 0.60, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "134", "descripcion": "LIBRO MI JARDIN", "cantidad": 6, "venta": 2.10, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "135", "descripcion": "FUNDA PROTECTORA OFICIO", "cantidad": 20, "venta": 0.20, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "136", "descripcion": "CARPETA MARRON CARTA", "cantidad": 25, "venta": 0.45, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "137", "descripcion": "CARPETA MARON OFICIO", "cantidad": 25, "venta": 0.55, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "138", "descripcion": "CARPETA AMARILLA CARTA", "cantidad": 0, "venta": 0.00, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "139", "descripcion": "CARPETA AMARILLA OFICIO", "cantidad": 0, "venta": 0.00, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "140", "descripcion": "LIBRETA 5 MATERIA", "cantidad": 6, "venta": 5.00, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "141", "descripcion": "TEMPERA OSI", "cantidad": 3, "venta": 1.50, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "142", "descripcion": "COMPAS POINTER", "cantidad": 6, "venta": 1.30, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "143", "descripcion": "SILICON EN BARRA DELGADO", "cantidad": 16, "venta": 0.25, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "144", "descripcion": "SILICON EN BARRA GRUESO", "cantidad": 25, "venta": 0.35, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "145", "descripcion": "PALETA COLORES", "cantidad": 5, "venta": 0.60, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "146", "descripcion": "PALETAS MARRON", "cantidad": 0, "venta": 0.00, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "147", "descripcion": "MINAS", "cantidad": 48, "venta": 0.20, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "148", "descripcion": "BORRADOR FABER CASTELLAN", "cantidad": 20, "venta": 0.25, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "149", "descripcion": "BORRADOR CRISVI", "cantidad": 20, "venta": 0.25, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "150", "descripcion": "SACAPUNTAS GRANDE CON DEPOSITO 2", "cantidad": 5, "venta": 0.50, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "151", "descripcion": "SACAPUNTAS CON BORRADOR", "cantidad": 19, "venta": 0.50, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "152", "descripcion": "GANCHOS PARA CARPETA", "cantidad": 30, "venta": 0.15, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "153", "descripcion": "SACAPUNTAS DE HIERRO", "cantidad": 48, "venta": 0.20, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "154", "descripcion": "ENGRAPADORA PEQUEÑA", "cantidad": 4, "venta": 2.50, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "155", "descripcion": "PORTAMINAS", "cantidad": 19, "venta": 0.80, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "156", "descripcion": "REGLAS POINTER", "cantidad": 6, "venta": 0.80, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "157", "descripcion": "REGLA ECONOMICA", "cantidad": 19, "venta": 0.50, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "158", "descripcion": "LAPIZ POINTER Y CRISVI", "cantidad": 83, "venta": 0.25, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "159", "descripcion": "LAPIZ MONGOL", "cantidad": 60, "venta": 0.35, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "160", "descripcion": "CORRECTOR TIPO LAPIZ", "cantidad": 12, "venta": 0.50, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "161", "descripcion": "PINCEL ECONOMICO", "cantidad": 36, "venta": 0.20, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "162", "descripcion": "LAPIZ BICOLOR", "cantidad": 12, "venta": 0.35, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "163", "descripcion": "LAPICERO POINTER", "cantidad": 24, "venta": 0.25, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "164", "descripcion": "ESCARCHA POTE", "cantidad": 36, "venta": 0.45, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "165", "descripcion": "CINTA ESCOLAR", "cantidad": 12, "venta": 0.40, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "166", "descripcion": "PEGA STICK KAISUO", "cantidad": 20, "venta": 0.50, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "167", "descripcion": "SILICON LIQUIDO 60 ML REGIONAL DEPOT", "cantidad": 8, "venta": 1.20, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "168", "descripcion": "PEGA BLANCA 120 ML REGIONAL", "cantidad": 6, "venta": 0.85, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "169", "descripcion": "PEGA BLANCA 60ML REGIONAL", "cantidad": 18, "venta": 0.65, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "170", "descripcion": "PEGA BLANCA 40 ML REGIONAL", "cantidad": 24, "venta": 0.50, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "171", "descripcion": "PAPEL SEDA", "cantidad": 194, "venta": 0.20, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "172", "descripcion": "PAPEL SEDA CON DETALLE", "cantidad": 20, "venta": 0.10, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "173", "descripcion": "PAPEL CELOFAN TRANSPARENTE", "cantidad": 15, "venta": 0.70, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "174", "descripcion": "CUADERNO VARIOS", "cantidad": 58, "venta": 0.95, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "175", "descripcion": "LIBRETA 1 MATERIA", "cantidad": 21, "venta": 1.20, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "176", "descripcion": "ANIME", "cantidad": 9, "venta": 2.00, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "178", "descripcion": "PINTURA AL FRIO", "cantidad": 143, "venta": 0.75, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "179", "descripcion": "LAPICERO DE GEL POINTER", "cantidad": 8, "venta": 0.60, "ubicacion": "TABLA ACANALADA ESCOLAR"},
    {"codigo": "301", "descripcion": "COMPACTO MONREVE", "cantidad": 19, "venta": 1.47, "ubicacion": "VITRINA 1"},
    {"codigo": "302", "descripcion": "COMPACTO NAILEN", "cantidad": 6, "venta": 1.00, "ubicacion": "VITRINA 1"},
    {"codigo": "303", "descripcion": "COMPACTO WINCOLOR", "cantidad": 39, "venta": 0.90, "ubicacion": "VITRINA 1"},
    {"codigo": "304", "descripcion": "SEMI ELLYS NAII", "cantidad": 6, "venta": 1.60, "ubicacion": "VITRINA 1"},
    {"codigo": "305", "descripcion": "SEMI MOMBRAY LAZO", "cantidad": 20, "venta": 1.50, "ubicacion": "VITRINA 1"},
    {"codigo": "306", "descripcion": "SEMI MOMBRAY BASE", "cantidad": 21, "venta": 1.60, "ubicacion": "VITRINA 1"},
    {"codigo": "307", "descripcion": "BASE RUBBER MOMBRAY", "cantidad": 14, "venta": 1.50, "ubicacion": "VITRINA 1"},
    {"codigo": "308", "descripcion": "NUDE MOMBRAY", "cantidad": 15, "venta": 1.60, "ubicacion": "VITRINA 1"},
    {"codigo": "309", "descripcion": "BASE COAT MOMBRAY LAZO", "cantidad": 4, "venta": 1.50, "ubicacion": "VITRINA 1"},
    {"codigo": "310", "descripcion": "TOP COAT MOMBRAY LAZO", "cantidad": 2, "venta": 1.50, "ubicacion": "VITRINA 1"},
    {"codigo": "311", "descripcion": "FINISH GEL MOMBRAY DORADA", "cantidad": 3, "venta": 1.60, "ubicacion": "VITRINA 1"},
    {"codigo": "312", "descripcion": "RUBBER TRANSPARENTE MOMBRAY", "cantidad": 3, "venta": 1.40, "ubicacion": "VITRINA 1"},
    {"codigo": "313", "descripcion": "6 EN 1 MOMBRAY", "cantidad": 3, "venta": 1.50, "ubicacion": "VITRINA 1"},
    {"codigo": "314", "descripcion": "SEMI ELLYS NAIL NEGRA", "cantidad": 2, "venta": 1.60, "ubicacion": "VITRINA 1"},
    {"codigo": "315", "descripcion": "RUBBER BASE M Y", "cantidad": 1, "venta": 1.40, "ubicacion": "VITRINA 1"},
    {"codigo": "316", "descripcion": "ESMALTE MAXEL TRADICIONAL", "cantidad": 67, "venta": 0.95, "ubicacion": "VITRINA 1"},
    {"codigo": "317", "descripcion": "ESMALTE VARIOS", "cantidad": 17, "venta": 0.50, "ubicacion": "VITRINA 1"},
    {"codigo": "318", "descripcion": "ESMALTE MOMBRAY TRADICIONAL", "cantidad": 52, "venta": 0.95, "ubicacion": "VITRINA 1"},
    {"codigo": "319", "descripcion": "RELOJ REDONDO COLORES", "cantidad": 9, "venta": 2.20, "ubicacion": "VITRINA 1"},
    {"codigo": "320", "descripcion": "RELOJ CUADRADO COLORES", "cantidad": 5, "venta": 2.50, "ubicacion": "VITRINA 1"},
    {"codigo": "321", "descripcion": "MAYA DONAS", "cantidad": 6, "venta": 1.00, "ubicacion": "VITRINA 1"},
    {"codigo": "323", "descripcion": "NAVAJA ACERO BARBERIA ROJA AZUL", "cantidad": 3, "venta": 2.80, "ubicacion": "VITRINA 1"},
    {"codigo": "324", "descripcion": "CERA PARA CABELLO VANGINS", "cantidad": 4, "venta": 2.00, "ubicacion": "VITRINA 1"},
    {"codigo": "325", "descripcion": "BROCHA BARBERIA", "cantidad": 1, "venta": 1.30, "ubicacion": "VITRINA 1"},
    {"codigo": "326", "descripcion": "ENVASE SPRAY BARBERIA", "cantidad": 2, "venta": 1.00, "ubicacion": "VITRINA 1"},
    {"codigo": "327", "descripcion": "MAQUINA DE BARBA MEILIS", "cantidad": 1, "venta": 7.00, "ubicacion": "VITRINA 1"},
    {"codigo": "328", "descripcion": "NAVAJA ACERO SALON CLIP", "cantidad": 1, "venta": 3.50, "ubicacion": "VITRINA 1"},
    {"codigo": "329", "descripcion": "COMBO PEINE BARBERIA PLASTICO NEGRO 5 UND", "cantidad": 3, "venta": 3.60, "ubicacion": "VITRINA 1"},
    {"codigo": "330", "descripcion": "PERFUME TUBITO 35ML DAMA CABALLERO NIÑO", "cantidad": 51, "venta": 1.25, "ubicacion": "VITRINA 1"},
    {"codigo": "331", "descripcion": "PERFUME SPLAS 52ML", "cantidad": 9, "venta": 1.30, "ubicacion": "VITRINA 1"},
    {"codigo": "332", "descripcion": "CREMA PERFUMADA CABALLERO 85ML", "cantidad": 6, "venta": 1.00, "ubicacion": "VITRINA 1"},
    {"codigo": "333", "descripcion": "PERFUME CUADRADA CABALLERO 60 MLML", "cantidad": 11, "venta": 2.50, "ubicacion": "VITRINA 1"},
    {"codigo": "334", "descripcion": "SEMI TIFANNY", "cantidad": 12, "venta": 1.35, "ubicacion": "VITRINA 1"},
    {"codigo": "335", "descripcion": "RELOJ DE CABALLERO NEGRO CASUAL", "cantidad": 3, "venta": 3.60, "ubicacion": "VITRINA 1"},
    {"codigo": "336", "descripcion": "CARTERA DE CABALLERO BOTON", "cantidad": 4, "venta": 3.00, "ubicacion": "VITRINA 1"},
    {"codigo": "337", "descripcion": "MINI ORGANIZADOR CABALLERO", "cantidad": 3, "venta": 3.00, "ubicacion": "VITRINA 1"},
    {"codigo": "338", "descripcion": "PORTA CARNET CABALLERO LLAVERO", "cantidad": 2, "venta": 1.00, "ubicacion": "VITRINA 1"},
    {"codigo": "339", "descripcion": "LAKA PARA CABALLERO", "cantidad": 7, "venta": 2.50, "ubicacion": "VITRINA 1"},
    {"codigo": "340", "descripcion": "SPRAY BARBER SHOP", "cantidad": 1, "venta": 3.50, "ubicacion": "VITRINA 1"},
    {"codigo": "341", "descripcion": "CREMA PERFUMADA DAMA 236 ML", "cantidad": 9, "venta": 1.50, "ubicacion": "VITRINA 1"},
    {"codigo": "342", "descripcion": "CORREAS DE DAMA", "cantidad": 6, "venta": 3.00, "ubicacion": "VITRINA 1"},
    {"codigo": "343", "descripcion": "MINI MONEDERO DAMA CIERRE", "cantidad": 3, "venta": 2.00, "ubicacion": "VITRINA 1"},
    {"codigo": "344", "descripcion": "MINI MONEDERO DAMA BOTON", "cantidad": 2, "venta": 1.85, "ubicacion": "VITRINA 1"},
    {"codigo": "345", "descripcion": "TIJERA PELUQUERIA PROFESIONAL", "cantidad": 3, "venta": 6.00, "ubicacion": "VITRINA 1"},
    {"codigo": "346", "descripcion": "TIJERA PELUQUERIA ECONOMICA", "cantidad": 3, "venta": 2.50, "ubicacion": "VITRINA 1"},
    {"codigo": "347", "descripcion": "CAPA DE BARBERIA PEQUEÑO", "cantidad": 4, "venta": 2.50, "ubicacion": "VITRINA 1"},
    {"codigo": "348", "descripcion": "COMBO COLONIA MINI 2", "cantidad": 1, "venta": 1.50, "ubicacion": "VITRINA 1"},
    {"codigo": "349", "descripcion": "COMBO COLONIA MINI 3", "cantidad": 1, "venta": 1.80, "ubicacion": "VITRINA 1"},
    {"codigo": "401", "descripcion": "BANDANA MAQUILLAJE JUVENIL", "cantidad": 3, "venta": 1.30, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "402", "descripcion": "BANDANA GRUESA DAMA", "cantidad": 10, "venta": 1.10, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "403", "descripcion": "CINTILLO NUBE DAMA", "cantidad": 9, "venta": 3.00, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "404", "descripcion": "COLITA COLORES 6 UND", "cantidad": 60, "venta": 0.35, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "405", "descripcion": "COLITA COLORES LAZO 6 UND", "cantidad": 6, "venta": 0.50, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "406", "descripcion": "COLITAS COLORES MINI 6 UND", "cantidad": 20, "venta": 0.30, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "407", "descripcion": "PINZAS CLASICAS PAQ", "cantidad": 5, "venta": 0.80, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "408", "descripcion": "PAQUETE DE COLITAS MINI 30 UND", "cantidad": 19, "venta": 1.10, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "409", "descripcion": "PIOJITOS ARO 9 UND", "cantidad": 6, "venta": 0.80, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "410", "descripcion": "PAQUETE PIOJITOS CROMADOS 30 UND", "cantidad": 5, "venta": 2.10, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "411", "descripcion": "PAQUETE PIOJITOS MATE 30 UND", "cantidad": 5, "venta": 1.90, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "412", "descripcion": "PINZA DORADA C/ PERLA", "cantidad": 12, "venta": 0.80, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "413", "descripcion": "CRAPA P/ CABELLO BOLSITA 20 UND", "cantidad": 9, "venta": 0.50, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "414", "descripcion": "GRAPA P/ CABELLO PLASTICO", "cantidad": 2, "venta": 0.90, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "415", "descripcion": "PAQUETE COLITAS CLASICAS", "cantidad": 2, "venta": 1.00, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "416", "descripcion": "PAQQUETE COLITAS DECORADAS", "cantidad": 12, "venta": 1.20, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "417", "descripcion": "PAQUETE DE COLITAS NEGRAS MINI", "cantidad": 3, "venta": 1.30, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "418", "descripcion": "PAQUETE DE GANCHITOS CON COLAS", "cantidad": 2, "venta": 1.20, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "419", "descripcion": "PAQUETE DE GANCHITOS NIÑAS", "cantidad": 2, "venta": 1.40, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "420", "descripcion": "PAQUETE DE PINZA MINI 6 UND", "cantidad": 4, "venta": 1.00, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "421", "descripcion": "PAQUETE DE PINZA FRUTAS NINA", "cantidad": 9, "venta": 0.70, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "422", "descripcion": "STICKER PARA CABELLO", "cantidad": 10, "venta": 0.80, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "423", "descripcion": "PAQUETE DE COLAS MEDIANA 36 UND", "cantidad": 2, "venta": 2.00, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "424", "descripcion": "LIGAS COLORES NEON", "cantidad": 7, "venta": 0.55, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "425", "descripcion": "LIGAS GRUESAS", "cantidad": 34, "venta": 0.40, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "426", "descripcion": "LIGAS DELGADAS", "cantidad": 32, "venta": 0.35, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "427", "descripcion": "GANCHOS LENTEJUELAS PAR", "cantidad": 14, "venta": 2.00, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "428", "descripcion": "GANCHOS LENTEJUELAS UNIDAD", "cantidad": 3, "venta": 0.80, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "429", "descripcion": "GANCHOS KUROMI PAQ PLASTICO", "cantidad": 2, "venta": 2.00, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "430", "descripcion": "GANCHOS VARIOS PAQUETE", "cantidad": 22, "venta": 1.25, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "431", "descripcion": "LLAVERO CON ESPEJO DAMA", "cantidad": 2, "venta": 1.00, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "432", "descripcion": "PAÑOLETAS", "cantidad": 6, "venta": 1.00, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "433", "descripcion": "BROCHA PARA TINTE", "cantidad": 1, "venta": 0.70, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "434", "descripcion": "CEPILLO NEGRO CLASICO PEQUEÑO", "cantidad": 2, "venta": 3.10, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "435", "descripcion": "CEPILLO P/ CABELLO CUADRADO", "cantidad": 3, "venta": 2.00, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "436", "descripcion": "PEINE SACAPIOJO METAL", "cantidad": 4, "venta": 1.50, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "437", "descripcion": "BORLAS MAQUILLAJE 4 UND", "cantidad": 4, "venta": 1.40, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "438", "descripcion": "BORLAS MAQUILLAJE CORAZON 2 UND", "cantidad": 2, "venta": 1.10, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "439", "descripcion": "UNAS DECORADAS BONITO", "cantidad": 27, "venta": 1.40, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "440", "descripcion": "UNAS DE NINA KIT", "cantidad": 6, "venta": 1.50, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "441", "descripcion": "UNAS P/PIES 120 UND MOMBRAY", "cantidad": 4, "venta": 1.10, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "442", "descripcion": "UNAS JELLYS CUADRADA 100 UND MONBRAY", "cantidad": 2, "venta": 1.10, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "443", "descripcion": "UNAS JELLYS CUADRADAS 240 UND", "cantidad": 2, "venta": 2.10, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "444", "descripcion": "PESTANAS MAC POR PUNTOS", "cantidad": 24, "venta": 1.00, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "445", "descripcion": "UNAS 3D", "cantidad": 3, "venta": 2.00, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "446", "descripcion": "RIZADOR DE PESTANAS ECONOMICO", "cantidad": 4, "venta": 1.50, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "447", "descripcion": "PERFILADOR DE CEJAS 3 UND", "cantidad": 13, "venta": 1.10, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "448", "descripcion": "PALITOS DE NARANJA 50 UND", "cantidad": 5, "venta": 1.50, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "449", "descripcion": "CEPILLO PARA CEJAS 50 UND", "cantidad": 5, "venta": 1.50, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "450", "descripcion": "PALETA PARA PIES PLASTICA", "cantidad": 6, "venta": 1.10, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "451", "descripcion": "GUILLOTINA PARA UNAS ECONOMICA", "cantidad": 3, "venta": 1.00, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "452", "descripcion": "BROCHA QUITA POLVO PARA UNAS", "cantidad": 5, "venta": 1.00, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "453", "descripcion": "SET DE BROCHA SIRENA MAQUILLAJE SET 3", "cantidad": 3, "venta": 1.10, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "454", "descripcion": "GORRO TERMICO 1 UND", "cantidad": 4, "venta": 1.00, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "455", "descripcion": "GORRO PARA PLANCHADO 2 UND", "cantidad": 12, "venta": 0.70, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "456", "descripcion": "PINCEL LINER 3 UND", "cantidad": 2, "venta": 1.30, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "458", "descripcion": "EFECTO ESPEJO P/UNAS", "cantidad": 4, "venta": 2.00, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "459", "descripcion": "SELLO P/UNAS TRANSPARENTE", "cantidad": 3, "venta": 1.00, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "460", "descripcion": "CORTA CUTICULA PLASTICO", "cantidad": 6, "venta": 0.70, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "461", "descripcion": "CORTA CUTICULA METAL ECONOMICO", "cantidad": 2, "venta": 1.50, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "462", "descripcion": "PATA E CABRA P/ UNAS PAQUETE 5 UND", "cantidad": 2, "venta": 1.10, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "463", "descripcion": "PIEDRA POME ECONOMICA", "cantidad": 6, "venta": 0.70, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "464", "descripcion": "REPUJADOR P/ UNAS", "cantidad": 5, "venta": 0.50, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "465", "descripcion": "GANCHOS NEGRO P/ CABELLO PEQ", "cantidad": 10, "venta": 0.70, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "466", "descripcion": "MOSTRARIO PARA MANICURISTAS", "cantidad": 5, "venta": 2.00, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "467", "descripcion": "KOALA UNIXES", "cantidad": 2, "venta": 2.00, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "468", "descripcion": "BANDANA NEGRA DAMA", "cantidad": 1, "venta": 1.00, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "469", "descripcion": "GORRO SATIN", "cantidad": 1, "venta": 4.00, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "470", "descripcion": "COLITAS SATIN", "cantidad": 6, "venta": 0.70, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "471", "descripcion": "CEPILLO PARA RIZOS", "cantidad": 1, "venta": 2.50, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "472", "descripcion": "PEINE CABALLERO PEQ", "cantidad": 12, "venta": 0.40, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "473", "descripcion": "ESPEJO REDONDO", "cantidad": 4, "venta": 1.50, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "474", "descripcion": "CAPA BARBERIA IMPRESA", "cantidad": 6, "venta": 6.00, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "475", "descripcion": "MARIPOSA CARNAVAL INFANTIL", "cantidad": 6, "venta": 2.50, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "476", "descripcion": "DELANTAR MANICURISTA", "cantidad": 2, "venta": 5.00, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "477", "descripcion": "GANCHOS DE DAMA COLORES", "cantidad": 6, "venta": 0.80, "ubicacion": "TABLA ACANALADA MAQUILLAJE"},
    {"codigo": "501", "descripcion": "PORTACOSMETICOS", "cantidad": 6, "venta": 3.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "502", "descripcion": "BOLSO ESCOLAR DINOSAURIO 3 PIEZAS", "cantidad": 1, "venta": 13.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "503", "descripcion": "BANDOLERO CABALLERO ECONOMICO", "cantidad": 3, "venta": 3.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "504", "descripcion": "BANDOLERO CABALLERO LOGO ROJO", "cantidad": 2, "venta": 4.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "505", "descripcion": "BANDOLERO CUADRADO CABALLEROS", "cantidad": 4, "venta": 4.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "506", "descripcion": "BANDOLERO CUADRADO PEQ DAMA", "cantidad": 3, "venta": 4.80, "ubicacion": "ESTANTE 1"},
    {"codigo": "507", "descripcion": "BANDOLERO DAMA REDONDO", "cantidad": 5, "venta": 5.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "508", "descripcion": "BANDOLERO MINI MARRON", "cantidad": 1, "venta": 2.50, "ubicacion": "ESTANTE 1"},
    {"codigo": "509", "descripcion": "MORRAL ESTAMPADO P/ DAMA", "cantidad": 2, "venta": 8.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "510", "descripcion": "CONTORNO FACIAL MINI", "cantidad": 20, "venta": 0.90, "ubicacion": "ESTANTE 1"},
    {"codigo": "511", "descripcion": "LONCHERA TERMICA NIÑA", "cantidad": 1, "venta": 3.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "512", "descripcion": "SOMBRA PARA OJOS LAMEILA", "cantidad": 6, "venta": 1.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "513", "descripcion": "PALETA DE SOMBRA MUÑECA", "cantidad": 2, "venta": 5.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "514", "descripcion": "PIGMENTOS PARA CEJAS M Y", "cantidad": 6, "venta": 1.40, "ubicacion": "ESTANTE 1"},
    {"codigo": "515", "descripcion": "PIGMENTO SUPER CRISTAL", "cantidad": 3, "venta": 4.50, "ubicacion": "ESTANTE 1"},
    {"codigo": "516", "descripcion": "SOBRE MASCARILLA FACIAL", "cantidad": 15, "venta": 0.55, "ubicacion": "ESTANTE 1"},
    {"codigo": "517", "descripcion": "SOBRE MASCARILLA FACIAL MEDIANA", "cantidad": 24, "venta": 0.65, "ubicacion": "ESTANTE 1"},
    {"codigo": "518", "descripcion": "SOBRE MASCARILLA PARA LABIOS", "cantidad": 12, "venta": 0.45, "ubicacion": "ESTANTE 1"},
    {"codigo": "519", "descripcion": "SOBRE MASCARILLA PARA OJERAS", "cantidad": 15, "venta": 0.45, "ubicacion": "ESTANTE 1"},
    {"codigo": "520", "descripcion": "MASCARILLA PUNTO NEGRO 3 PASOS", "cantidad": 12, "venta": 0.80, "ubicacion": "ESTANTE 1"},
    {"codigo": "521", "descripcion": "PROTECTOR SOLAR SPRAY GRENOBIL", "cantidad": 3, "venta": 2.80, "ubicacion": "ESTANTE 1"},
    {"codigo": "522", "descripcion": "PROTECTOR SOLAR BASE BIODERMA", "cantidad": 1, "venta": 2.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "523", "descripcion": "ACEITE PARA CABELLO MASAJE TIFANNY", "cantidad": 7, "venta": 1.50, "ubicacion": "ESTANTE 1"},
    {"codigo": "524", "descripcion": "ESPUMA FACIAL LIMPIADORA 120ML", "cantidad": 5, "venta": 3.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "525", "descripcion": "CREMA LIMPIADORA VITAMINA C 100ML", "cantidad": 1, "venta": 2.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "526", "descripcion": "EXFOLAINTE FACIAL HUDABEAUTY", "cantidad": 2, "venta": 2.20, "ubicacion": "ESTANTE 1"},
    {"codigo": "527", "descripcion": "ESPONJA LIMPIADORA SKINCARE", "cantidad": 3, "venta": 1.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "528", "descripcion": "DESMAQUILLANTE 60ML ROSADO", "cantidad": 6, "venta": 1.50, "ubicacion": "ESTANTE 1"},
    {"codigo": "529", "descripcion": "AGUA MISCELAR RIBIABEAUTY 100ML", "cantidad": 6, "venta": 2.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "530", "descripcion": "CREMA LIMPIADORA DE COCO 50 ML", "cantidad": 2, "venta": 0.80, "ubicacion": "ESTANTE 1"},
    {"codigo": "531", "descripcion": "FIJADOR DE MAQUILAJE VITAMINA C 60 ML", "cantidad": 2, "venta": 2.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "532", "descripcion": "SERUM 24K", "cantidad": 2, "venta": 1.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "533", "descripcion": "SERUM VITAMINA C", "cantidad": 1, "venta": 2.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "534", "descripcion": "SERUM VARIOS", "cantidad": 4, "venta": 1.50, "ubicacion": "ESTANTE 1"},
    {"codigo": "535", "descripcion": "COLOR 1 NEGRO", "cantidad": 13, "venta": 0.95, "ubicacion": "ESTANTE 1"},
    {"codigo": "536", "descripcion": "BIGEN ECONIMICO", "cantidad": 18, "venta": 1.10, "ubicacion": "ESTANTE 1"},
    {"codigo": "537", "descripcion": "VASITO CRISTAL", "cantidad": 12, "venta": 0.50, "ubicacion": "ESTANTE 1"},
    {"codigo": "538", "descripcion": "CAJA TOALLAS", "cantidad": 3, "venta": 1.50, "ubicacion": "ESTANTE 1"},
    {"codigo": "539", "descripcion": "GEL FACIAL ALOE VERA Y PARA PESTANAS", "cantidad": 3, "venta": 2.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "540", "descripcion": "PEGA SALOM PRO ORIGINAL", "cantidad": 3, "venta": 3.90, "ubicacion": "ESTANTE 1"},
    {"codigo": "541", "descripcion": "PEGA ARDELL ORIGINAL", "cantidad": 3, "venta": 7.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "542", "descripcion": "PEGA SALOM PRO IMITACION", "cantidad": 6, "venta": 1.40, "ubicacion": "ESTANTE 1"},
    {"codigo": "546", "descripcion": "ESPONJA FASCIAL CON BORLA 3 PIEZAS", "cantidad": 2, "venta": 1.15, "ubicacion": "ESTANTE 1"},
    {"codigo": "547", "descripcion": "ESPONJA FACIAL 1 UND", "cantidad": 2, "venta": 0.60, "ubicacion": "ESTANTE 1"},
    {"codigo": "548", "descripcion": "ESPONJA FACIAL 3 UND", "cantidad": 16, "venta": 1.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "552", "descripcion": "COLONIA MINI CABALLERO", "cantidad": 40, "venta": 0.50, "ubicacion": "ESTANTE 1"},
    {"codigo": "553", "descripcion": "PEGA ARDELL IMITACION", "cantidad": 8, "venta": 1.60, "ubicacion": "ESTANTE 1"},
    {"codigo": "554", "descripcion": "SOMBRA PARA OJOS 6 TONOS", "cantidad": 5, "venta": 1.50, "ubicacion": "ESTANTE 1"},
    {"codigo": "555", "descripcion": "SOMBRA PARA CEJAS 3 TONOS KEBOSI", "cantidad": 6, "venta": 1.30, "ubicacion": "ESTANTE 1"},
    {"codigo": "556", "descripcion": "SOMBRA PARA CEJAS + GEL", "cantidad": 6, "venta": 1.40, "ubicacion": "ESTANTE 1"},
    {"codigo": "557", "descripcion": "SOMBRA PARA CEJAS MISS FON CUADRADA", "cantidad": 3, "venta": 1.40, "ubicacion": "ESTANTE 1"},
    {"codigo": "558", "descripcion": "SOMBRA PARA CEJAS MANZANA", "cantidad": 5, "venta": 1.20, "ubicacion": "ESTANTE 1"},
    {"codigo": "559", "descripcion": "POMADA PARA CEJAS NUDE", "cantidad": 2, "venta": 1.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "560", "descripcion": "CORRECTOR FACIAL HUXIABEAUTY", "cantidad": 18, "venta": 0.90, "ubicacion": "ESTANTE 1"},
    {"codigo": "561", "descripcion": "CORRECTOR BB FRESH", "cantidad": 24, "venta": 1.20, "ubicacion": "ESTANTE 1"},
    {"codigo": "562", "descripcion": "POLVO SUELTO MEIKE GLAMOUR", "cantidad": 6, "venta": 1.40, "ubicacion": "ESTANTE 1"},
    {"codigo": "563", "descripcion": "TOALLAS PAQ PEQ ROSADA", "cantidad": 2, "venta": 0.30, "ubicacion": "ESTANTE 1"},
    {"codigo": "564", "descripcion": "PINCEL PARA CEJAS 2 EN 1", "cantidad": 12, "venta": 0.75, "ubicacion": "ESTANTE 1"},
    {"codigo": "565", "descripcion": "PINCEL QUIRURGICO", "cantidad": 10, "venta": 1.50, "ubicacion": "ESTANTE 1"},
    {"codigo": "566", "descripcion": "TIJERA PARA CEJAS", "cantidad": 6, "venta": 1.40, "ubicacion": "ESTANTE 1"},
    {"codigo": "567", "descripcion": "ENVASE LAVA CEJAS", "cantidad": 3, "venta": 3.50, "ubicacion": "ESTANTE 1"},
    {"codigo": "568", "descripcion": "SET CON ESPEJO PARA CEJAS", "cantidad": 6, "venta": 0.90, "ubicacion": "ESTANTE 1"},
    {"codigo": "569", "descripcion": "BROCHA PARA CEJAS", "cantidad": 6, "venta": 1.40, "ubicacion": "ESTANTE 1"},
    {"codigo": "570", "descripcion": "ESPUMA LIMPIADORA P CEJAS", "cantidad": 3, "venta": 3.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "571", "descripcion": "ENVOPLAST PARA CEJAS", "cantidad": 2, "venta": 1.50, "ubicacion": "ESTANTE 1"},
    {"codigo": "572", "descripcion": "VERNIER", "cantidad": 6, "venta": 2.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "573", "descripcion": "LAPIZ DE CEJAS FASHION CAJA", "cantidad": 12, "venta": 0.80, "ubicacion": "ESTANTE 1"},
    {"codigo": "574", "descripcion": "MICROBLANDING", "cantidad": 24, "venta": 0.90, "ubicacion": "ESTANTE 1"},
    {"codigo": "575", "descripcion": "LAPIZ DE OJOS MAC", "cantidad": 24, "venta": 0.35, "ubicacion": "ESTANTE 1"},
    {"codigo": "576", "descripcion": "ESPONJA KISS PLUS 2 PIEZAS", "cantidad": 3, "venta": 2.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "577", "descripcion": "ESPONJA KISS PLUS 3 PIEZAS", "cantidad": 3, "venta": 1.20, "ubicacion": "ESTANTE 1"},
    {"codigo": "578", "descripcion": "CERA BODY", "cantidad": 3, "venta": 3.20, "ubicacion": "ESTANTE 1"},
    {"codigo": "579", "descripcion": "CERA AZULENO", "cantidad": 3, "venta": 5.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "580", "descripcion": "OLLA PARA CERA", "cantidad": 3, "venta": 9.80, "ubicacion": "ESTANTE 1"},
    {"codigo": "581", "descripcion": "BANDAS PARA DEPILAR", "cantidad": 3, "venta": 2.50, "ubicacion": "ESTANTE 1"},
    {"codigo": "582", "descripcion": "PALETAS PARA CERA 4 UND", "cantidad": 25, "venta": 0.20, "ubicacion": "ESTANTE 1"},
    {"codigo": "583", "descripcion": "GUANTES LATEX PAR", "cantidad": 50, "venta": 0.25, "ubicacion": "ESTANTE 1"},
    {"codigo": "584", "descripcion": "ALGODÓN MOPA PEQUEÑA", "cantidad": 6, "venta": 1.10, "ubicacion": "ESTANTE 1"},
    {"codigo": "585", "descripcion": "PALITOS DE NARAJNJA 3 UND", "cantidad": 15, "venta": 0.20, "ubicacion": "ESTANTE 1"},
    {"codigo": "586", "descripcion": "CEPILLO PARA CEJAS Y PESTAÑAS 3UND", "cantidad": 15, "venta": 0.20, "ubicacion": "ESTANTE 1"},
    {"codigo": "587", "descripcion": "ESPONJA UNIDAD BOLSITA", "cantidad": 4, "venta": 0.40, "ubicacion": "ESTANTE 1"},
    {"codigo": "588", "descripcion": "TOALLA FACIAL", "cantidad": 12, "venta": 1.00, "ubicacion": "ESTANTE 1"},
    {"codigo": "601", "descripcion": "MASCARA PARA PESTANAS MAC 2 EN 1", "cantidad": 12, "venta": 2.00, "ubicacion": "ESTANTE 2"},
    {"codigo": "602", "descripcion": "MASCARA DE PESTANAS HUXIABEAUTY", "cantidad": 24, "venta": 1.00, "ubicacion": "ESTANTE 2"},
    {"codigo": "603", "descripcion": "MASCARA DE PESTANA +GEL PARA CEJAS", "cantidad": 6, "venta": 1.50, "ubicacion": "ESTANTE 2"},
    {"codigo": "604", "descripcion": "RIZADOR DE PESTANAS CROMADO", "cantidad": 5, "venta": 1.70, "ubicacion": "ESTANTE 2"},
    {"codigo": "605", "descripcion": "BASE FACIAL HUXIABEAUTY", "cantidad": 19, "venta": 0.90, "ubicacion": "ESTANTE 2"},
    {"codigo": "606", "descripcion": "BASE FACIAL COMFORT BEAUTY", "cantidad": 10, "venta": 0.90, "ubicacion": "ESTANTE 2"},
    {"codigo": "607", "descripcion": "LABIAL OSO", "cantidad": 24, "venta": 1.00, "ubicacion": "ESTANTE 2"},
    {"codigo": "608", "descripcion": "DELINEADOR LIQUIDO CROMADO", "cantidad": 24, "venta": 0.80, "ubicacion": "ESTANTE 2"},
    {"codigo": "609", "descripcion": "POLVO DE HADAS", "cantidad": 24, "venta": 1.20, "ubicacion": "ESTANTE 2"},
    {"codigo": "610", "descripcion": "PRIMER FACIAL", "cantidad": 5, "venta": 0.85, "ubicacion": "ESTANTE 2"},
    {"codigo": "611", "descripcion": "PINTURA LABIAL TRADICIONAL", "cantidad": 12, "venta": 0.95, "ubicacion": "ESTANTE 2"},
    {"codigo": "612", "descripcion": "PINTURA LABIAL MATE", "cantidad": 12, "venta": 0.95, "ubicacion": "ESTANTE 2"},
    {"codigo": "613", "descripcion": "LAPIZ LABIAL CONTORNO", "cantidad": 6, "venta": 0.60, "ubicacion": "ESTANTE 2"},
    {"codigo": "614", "descripcion": "LIP GLOS PINTURA TRADICIONAL", "cantidad": 12, "venta": 0.90, "ubicacion": "ESTANTE 2"},
    {"codigo": "615", "descripcion": "PINTURA NUDE MATE LARGA DURACION", "cantidad": 12, "venta": 1.00, "ubicacion": "ESTANTE 2"},
    {"codigo": "616", "descripcion": "RUBOR GELATINA", "cantidad": 12, "venta": 1.50, "ubicacion": "ESTANTE 2"},
    {"codigo": "617", "descripcion": "RUBOR LIQUIDO", "cantidad": 8, "venta": 1.60, "ubicacion": "ESTANTE 2"},
    {"codigo": "618", "descripcion": "TINTA PARA LABIOS", "cantidad": 72, "venta": 1.00, "ubicacion": "ESTANTE 2"},
    {"codigo": "619", "descripcion": "COLONIA DUO COLONIA + CREMA", "cantidad": 17, "venta": 1.80, "ubicacion": "ESTANTE 2"},
    {"codigo": "620", "descripcion": "COLONIA MINI DAMA", "cantidad": 4, "venta": 0.80, "ubicacion": "ESTANTE 2"},
    {"codigo": "621", "descripcion": "BRILLO DE LABIOS P NINAS FRUTAS", "cantidad": 46, "venta": 0.90, "ubicacion": "ESTANTE 2"},
    {"codigo": "622", "descripcion": "VASELINA DONA", "cantidad": 6, "venta": 1.00, "ubicacion": "ESTANTE 2"},
    {"codigo": "623", "descripcion": "VASELINA CARITA FELIZ", "cantidad": 12, "venta": 0.85, "ubicacion": "ESTANTE 2"},
    {"codigo": "624", "descripcion": "ILUMINADOR CORAZON", "cantidad": 12, "venta": 1.40, "ubicacion": "ESTANTE 2"},
    {"codigo": "625", "descripcion": "ILUMINADOR EN POLVO", "cantidad": 6, "venta": 1.40, "ubicacion": "ESTANTE 2"},
    {"codigo": "626", "descripcion": "BRILLO TRANSPARENTE DAMA", "cantidad": 24, "venta": 0.85, "ubicacion": "ESTANTE 2"},
    {"codigo": "627", "descripcion": "LIP GLOSS 2 EN 1", "cantidad": 24, "venta": 1.00, "ubicacion": "ESTANTE 2"},
    {"codigo": "628", "descripcion": "VASELINA VASEINA", "cantidad": 8, "venta": 0.80, "ubicacion": "ESTANTE 2"},
    {"codigo": "629", "descripcion": "BALSAMO FRUTAS MELOCOTON", "cantidad": 6, "venta": 0.95, "ubicacion": "ESTANTE 2"},
    {"codigo": "630", "descripcion": "PINTURA MAGICA", "cantidad": 12, "venta": 0.80, "ubicacion": "ESTANTE 2"},
    {"codigo": "701", "descripcion": "LAMPARA PARA UNAS 56 W MOMBRAY", "cantidad": 2, "venta": 9.00, "ubicacion": "ESTANTE 3"},
    {"codigo": "702", "descripcion": "LAMPARA JELLYS MOMBRAY", "cantidad": 3, "venta": 5.00, "ubicacion": "ESTANTE 3"},
    {"codigo": "703", "descripcion": "MINI LAMPARA SEMI", "cantidad": 3, "venta": 2.00, "ubicacion": "ESTANTE 3"},
    {"codigo": "704", "descripcion": "TINTE PARA CABELLO LOVIA PEQUEÑO", "cantidad": 75, "venta": 0.95, "ubicacion": "ESTANTE 3"},
    {"codigo": "705", "descripcion": "TINTE PARA CABELLO GRANDE", "cantidad": 11, "venta": 2.00, "ubicacion": "ESTANTE 3"},
    {"codigo": "706", "descripcion": "AGUA OXIGENADA PARA CABELLO", "cantidad": 18, "venta": 1.00, "ubicacion": "ESTANTE 3"},
    {"codigo": "707", "descripcion": "SILICON PARA CABELLO", "cantidad": 2, "venta": 5.00, "ubicacion": "ESTANTE 3"},
    {"codigo": "708", "descripcion": "REPARADOR DE PUNTAS PARA CABELLO", "cantidad": 1, "venta": 1.20, "ubicacion": "ESTANTE 3"},
    {"codigo": "709", "descripcion": "MASCARILLA KARSELL SOBRE", "cantidad": 12, "venta": 1.15, "ubicacion": "ESTANTE 3"},
    {"codigo": "710", "descripcion": "MATIZADOR LOVIA", "cantidad": 6, "venta": 0.80, "ubicacion": "ESTANTE 3"},
    {"codigo": "711", "descripcion": "DECOLORANTE RAPID BLUE", "cantidad": 4, "venta": 2.80, "ubicacion": "ESTANTE 3"},
    {"codigo": "712", "descripcion": "PEGA LOKA", "cantidad": 40, "venta": 0.40, "ubicacion": "ESTANTE 3"},
    {"codigo": "713", "descripcion": "NOVEX BLINDAGEM", "cantidad": 0, "venta": 2.00, "ubicacion": "ESTANTE 3"},
    {"codigo": "714", "descripcion": "PESTANAS MAC 30P", "cantidad": 6, "venta": 1.50, "ubicacion": "ESTANTE 3"},
    {"codigo": "715", "descripcion": "TINTE PARA CABELLO TUBITO 60ML", "cantidad": 1, "venta": 0.00, "ubicacion": "ESTANTE 3"},
    {"codigo": "716", "descripcion": "TINTE PARA CABELLO TUBITO 100ML", "cantidad": 1, "venta": 0.00, "ubicacion": "ESTANTE 3"},
    {"codigo": "717", "descripcion": "DECOLORANTE LOVIA", "cantidad": 3, "venta": 0.00, "ubicacion": "ESTANTE 3"},
    {"codigo": "719", "descripcion": "PESTANAS MOMBRAY 20P", "cantidad": 13, "venta": 1.90, "ubicacion": "ESTANTE 3"},
    {"codigo": "720", "descripcion": "BANDOLEROS MOMBRAY", "cantidad": 3, "venta": 6.00, "ubicacion": "ESTANTE 3"},
    {"codigo": "721", "descripcion": "MONEDERO MOMBRAY", "cantidad": 1, "venta": 4.00, "ubicacion": "ESTANTE 3"},
    {"codigo": "722", "descripcion": "MATIZANTE LORIANN", "cantidad": 30, "venta": 1.20, "ubicacion": "ESTANTE 3"},
    {"codigo": "723", "descripcion": "ENVASE SPRAY", "cantidad": 2, "venta": 0.85, "ubicacion": "ESTANTE 3"},
    {"codigo": "724", "descripcion": "PINCEL VARIOS PARA UÑAS", "cantidad": 7, "venta": 0.50, "ubicacion": "ESTANTE 3"},
    {"codigo": "725", "descripcion": "PINCEL PARA POLYGEL", "cantidad": 6, "venta": 1.20, "ubicacion": "ESTANTE 3"},
    {"codigo": "726", "descripcion": "PINCEL LINER CON CRISTALES", "cantidad": 6, "venta": 1.60, "ubicacion": "ESTANTE 3"},
    {"codigo": "727", "descripcion": "PINZA PARA PESTAÑAS UND", "cantidad": 4, "venta": 0.70, "ubicacion": "ESTANTE 3"},
    {"codigo": "728", "descripcion": "PINZA PARA PESTANAS 2 UND", "cantidad": 5, "venta": 1.00, "ubicacion": "ESTANTE 3"},
    {"codigo": "729", "descripcion": "CRISTALES PARA UÑAS GRANDE", "cantidad": 8, "venta": 2.00, "ubicacion": "ESTANTE 3"},
    {"codigo": "730", "descripcion": "CRISTALES PARA UÑAS PEQ", "cantidad": 4, "venta": 1.70, "ubicacion": "ESTANTE 3"},
    {"codigo": "731", "descripcion": "SHAROSQUI PARA UÑAS", "cantidad": 11, "venta": 1.00, "ubicacion": "ESTANTE 3"},
    {"codigo": "732", "descripcion": "PESTAÑAS TIFANY SIRENA", "cantidad": 8, "venta": 1.90, "ubicacion": "ESTANTE 3"},
    {"codigo": "733", "descripcion": "PESTAÑAS TIFANY AZUL 20P", "cantidad": 20, "venta": 1.95, "ubicacion": "ESTANTE 3"},
    {"codigo": "734", "descripcion": "PEINE PARA PANCHADO", "cantidad": 21, "venta": 0.70, "ubicacion": "ESTANTE 3"},
    {"codigo": "735", "descripcion": "PINCEL ACRILICO ECONOMICO", "cantidad": 5, "venta": 0.60, "ubicacion": "ESTANTE 3"},
    {"codigo": "736", "descripcion": "PINCEL GEL ECONOMICO", "cantidad": 5, "venta": 0.40, "ubicacion": "ESTANTE 3"},
    {"codigo": "737", "descripcion": "EXFOLIANTE TIFANY", "cantidad": 6, "venta": 2.80, "ubicacion": "ESTANTE 3"},
    {"codigo": "738", "descripcion": "PEINE TRADICIONAL", "cantidad": 12, "venta": 0.75, "ubicacion": "ESTANTE 3"},
    {"codigo": "739", "descripcion": "LIMA SPONYI NARANJA", "cantidad": 6, "venta": 0.60, "ubicacion": "ESTANTE 3"},
    {"codigo": "740", "descripcion": "LIMA 100/180", "cantidad": 31, "venta": 0.45, "ubicacion": "ESTANTE 3"},
    {"codigo": "741", "descripcion": "TACOS PARA UÑAS", "cantidad": 10, "venta": 0.40, "ubicacion": "ESTANTE 3"},
    {"codigo": "742", "descripcion": "ALCOHOL PEQUEÑO", "cantidad": 10, "venta": 1.00, "ubicacion": "ESTANTE 3"},
    {"codigo": "743", "descripcion": "MONOMERO SUPER CRISTAL", "cantidad": 6, "venta": 2.90, "ubicacion": "ESTANTE 3"},
    {"codigo": "744", "descripcion": "PEGA P/UÑAS MX BON", "cantidad": 25, "venta": 0.85, "ubicacion": "ESTANTE 3"},
    {"codigo": "745", "descripcion": "ANTI HONGOS M Y", "cantidad": 4, "venta": 1.50, "ubicacion": "ESTANTE 3"},
    {"codigo": "746", "descripcion": "REMOVEDOR DE ESMALTE MOMBRAY", "cantidad": 2, "venta": 1.40, "ubicacion": "ESTANTE 3"},
    {"codigo": "747", "descripcion": "REMOVEDOR DE ESMALTE VALMY", "cantidad": 12, "venta": 1.50, "ubicacion": "ESTANTE 3"},
    {"codigo": "748", "descripcion": "QUIMICA ENDURECEDORA VALMY", "cantidad": 9, "venta": 0.80, "ubicacion": "ESTANTE 3"},
    {"codigo": "749", "descripcion": "CORTA UÑAS TRIM MEDIANO", "cantidad": 11, "venta": 0.70, "ubicacion": "ESTANTE 3"},
    {"codigo": "750", "descripcion": "GEL PARA CABELLO DAVEY", "cantidad": 3, "venta": 1.60, "ubicacion": "ESTANTE 3"},
    {"codigo": "751", "descripcion": "PUNTEROS P/ UNAS 5 UND", "cantidad": 5, "venta": 0.30, "ubicacion": "ESTANTE 3"},
    {"codigo": "752", "descripcion": "PINCEL LINER", "cantidad": 6, "venta": 0.50, "ubicacion": "ESTANTE 3"},
    {"codigo": "753", "descripcion": "PINCEL ACRILICO SIRENA", "cantidad": 3, "venta": 0.80, "ubicacion": "ESTANTE 3"},
    {"codigo": "754", "descripcion": "PESTAÑAS TIFANY 30P", "cantidad": 5, "venta": 2.15, "ubicacion": "ESTANTE 3"},
    {"codigo": "803", "descripcion": "ESCLAVA DAMA", "cantidad": 6, "venta": 1.60, "ubicacion": "BISUTERIA"},
    {"codigo": "804", "descripcion": "CADENA ROQUERA", "cantidad": 7, "venta": 2.00, "ubicacion": "BISUTERIA"},
    {"codigo": "805", "descripcion": "CADENA DE ACERO CABALLERO 2", "cantidad": 2, "venta": 2.90, "ubicacion": "BISUTERIA"},
    {"codigo": "806", "descripcion": "CADENA DE ACERO CABALLERO 1", "cantidad": 1, "venta": 2.70, "ubicacion": "BISUTERIA"},
    {"codigo": "807", "descripcion": "CADENA ACERO CABALLERO ECONOMICA", "cantidad": 5, "venta": 2.00, "ubicacion": "BISUTERIA"},
    {"codigo": "808", "descripcion": "CADENA INFANTIL ACERO", "cantidad": 4, "venta": 2.80, "ubicacion": "BISUTERIA"},
    {"codigo": "809", "descripcion": "PINZA METAL", "cantidad": 6, "venta": 1.00, "ubicacion": "BISUTERIA"},
    {"codigo": "810", "descripcion": "ARGOLLA MINI ACERO", "cantidad": 6, "venta": 1.00, "ubicacion": "BISUTERIA"},
    {"codigo": "811", "descripcion": "ARGOLLA PERLAS", "cantidad": 6, "venta": 1.50, "ubicacion": "BISUTERIA"},
    {"codigo": "812", "descripcion": "ARGOLLA PIEDRA", "cantidad": 5, "venta": 1.70, "ubicacion": "BISUTERIA"},
    {"codigo": "813", "descripcion": "ABRIDORES", "cantidad": 8, "venta": 0.40, "ubicacion": "BISUTERIA"},
    {"codigo": "814", "descripcion": "TOBILLERAS", "cantidad": 6, "venta": 1.80, "ubicacion": "BISUTERIA"},
    {"codigo": "815", "descripcion": "SARCILLOS CON IMAN", "cantidad": 24, "venta": 0.50, "ubicacion": "BISUTERIA"},
    {"codigo": "816", "descripcion": "ARGOLLAS LISAS 5", "cantidad": 6, "venta": 0.60, "ubicacion": "BISUTERIA"},
    {"codigo": "817", "descripcion": "ARGOLLAS LISAS 3", "cantidad": 6, "venta": 0.60, "ubicacion": "BISUTERIA"},
    {"codigo": "818", "descripcion": "ARGOLLAS LISAS 1", "cantidad": 6, "venta": 0.50, "ubicacion": "BISUTERIA"},
    {"codigo": "819", "descripcion": "JUEGO DE ACERO", "cantidad": 14, "venta": 1.10, "ubicacion": "BISUTERIA"},
    {"codigo": "820", "descripcion": "PEIRCING NARIZ", "cantidad": 24, "venta": 0.20, "ubicacion": "BISUTERIA"},
    {"codigo": "821", "descripcion": "ANILLOS NIÑA", "cantidad": 16, "venta": 1.00, "ubicacion": "BISUTERIA"},
    {"codigo": "822", "descripcion": "SARCILLOS HOMBRES", "cantidad": 108, "venta": 0.30, "ubicacion": "BISUTERIA"},
    {"codigo": "823", "descripcion": "TUNEL CABALLERO", "cantidad": 12, "venta": 0.50, "ubicacion": "BISUTERIA"},
    {"codigo": "824", "descripcion": "CINTILLOS GAMUZA", "cantidad": 6, "venta": 1.00, "ubicacion": "BISUTERIA"},
    {"codigo": "825", "descripcion": "CINTILLOS GAMUZA ESCARCHA", "cantidad": 6, "venta": 1.40, "ubicacion": "BISUTERIA"},
    {"codigo": "826", "descripcion": "CINTILLO NEGRO PIEDRA", "cantidad": 6, "venta": 1.40, "ubicacion": "BISUTERIA"},
    {"codigo": "827", "descripcion": "MORRAL + BANDOLERO+MONEDERO", "cantidad": 3, "venta": 14.50, "ubicacion": "BISUTERIA"},
    {"codigo": "828", "descripcion": "UÑAS CLASICAS BOLSITAS", "cantidad": 24, "venta": 0.25, "ubicacion": "BISUTERIA"},
    {"codigo": "829", "descripcion": "MIN GANCHO PLASTICO PERLA PAR", "cantidad": 3, "venta": 0.80, "ubicacion": "BISUTERIA"},
    {"codigo": "830", "descripcion": "GANCHO PLASTICO PERLA", "cantidad": 10, "venta": 0.0, "ubicacion": "BISUTERIA"}
]